variables:
  DOCKER_API_VERSION: "1.41"

services:
  - docker:27-dind

runner:
  tags:
    - inn-runner   # Replace with the tag you set during runner registration
  # image: ruby:3.1       # Matches the executor image you configured
  script:
    - echo "✅ Runner is working!"
    - sudo docker version           # Check docker version

include:
  - template: Auto-DevOps.gitlab-ci.yml
  