keycloak:
  admin_client_id: ams-admin-cli
  admin_client_secret: 9LOPP7kjr4qftH0YEFzJmGpTKTQisdyG
  domain: http://127.0.0.1:8080
  realm: INN-AMS
  redirect_uri: http://127.0.0.1:5000/auth/callback
  ui_client_id: inn-data-portal
  ui_client_secret: cCQnEiBgf1z75RKrPyyRxb3e0k7sFcpe
  refresh_token_expiry: 300
logging:
  level:
    app: INFO
    casbin: INFO
    root: INFO
    uvicorn: INFO
    uvicorn_access: INFO
    uvicorn_error: ERROR
system:
  reset: false
uvicorn:
  debug: true
  host: 127.0.0.1
  port: 5000
  reload: true
