uvicorn:
  host: 0.0.0.0
  port: 5000
  reset: false
  reload: true
  debug: true

logging:
  level:
    root: INFO
    uvicorn: INFO
    uvicorn_error: ERROR
    uvicorn_access: INFO
    casbin: INFO
    app: INFO
