uvicorn:
  host: 127.0.0.1
  port: 5000
  reload: true
  debug: true

logging:
  level:
    root: INFO
    uvicorn: INFO
    uvicorn_error: ERROR
    uvicorn_access: INFO
    casbin: INFO
    app: INFO

keycloak:
  domain: "http://localhost:8080"         # Base URL of your Keycloak server
  realm: "INN-AMS"                      # The realm you're using (e.g., "INN-Portal")
  client_id: "inn-data-portal"                   # The client ID registered in Keycloak
  client_secret: "your_client_secret"           # (Optional) Only if your client is confidential
  redirect_uri: "http://127.0.0.1:5000/auth/callback"  # Where Keycloak should redirect after login
  admin_username: "admin"
  admin_password: "admin"

system:
  reset: true