server {
    listen 80;
    listen [::]:80;
    server_name portal.orca.research.sfu.ca;
    server_tokens off;
    
    location ~ /.well-known/acme-challenge/ {
    #allow all;
    root /var/www/certbot;
    }
    
        location / {
        return 301 https://portal.orca.research.sfu.ca$request_uri;
    }

}

server {
    listen 443 default_server ssl http2;
    listen [::]:443 ssl http2;
    server_name portal.orca.research.sfu.ca www.portal.orca.research.sfu.ca;

    ssl_certificate /etc/letsencrypt/live/portal.orca.research.sfu.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/portal.orca.research.sfu.ca/privkey.pem;

       location / {
        root  /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }


    location /api{
        # proxy_pass http://10.5.0.5:8080;
        #proxy_pass http://back-end:8080;

        proxy_set_header   Host                 $http_host;
        proxy_set_header   X-Real-IP            $remote_addr;
        proxy_set_header   X-Forwarded-For      $proxy_add_x_forwarded_for;
    }


}
