services:
  ams-portal:
    build: ..
    container_name: ams-portal
    ports:
      - "${AMS_PORT:-8000}:8000"
    environment:
      - AMS_HOST=0.0.0.0
      - AMS_PORT=8000
    volumes:
      # Mount configuration files
      - ../config.yaml:/app/config.yaml:ro
      - ../core/settings/.env:/app/core/settings/.env:ro
      - ../core/settings/security/.secrets:/app/core/settings/security/.secrets:ro
      
      # Mount data directories (optional - for persistent storage configs)
      - ../core/settings/managers/endpoints/configs:/app/core/settings/managers/endpoints/configs
      - ../core/settings/managers/policies:/app/core/settings/managers/policies
      
      # Mount logs (optional - for log persistence)
      - ../loggers/logs:/app/loggers/logs
    depends_on:
      - keycloak
    networks:
      - ams-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: ams-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - ams-network
    restart: unless-stopped
    command: start-dev

volumes:
  keycloak_data:

networks:
  ams-network:
    driver: bridge