# Base Nomad job template for any service
# This template uses envsubst variables (${__VARIABLE__}) for substitution
# Variables are set in the GitLab CI pipeline

job "${__SERVICE__}-${__ENVIRONMENT__}" {
  datacenters = ${__DATACENTERS__}
  namespace   = "${__NAMESPACE__}"
  type        = "service"

  # Constraints to avoid specific nodes
  constraint {
    attribute = "${meta.role}"
    operator  = "!="
    value     = "rcg-ingress"
  }

  constraint {
    attribute = "${meta.role}"
    operator  = "!="
    value     = "ingress-server"
  }

  constraint {
    attribute = "${meta.role}"
    operator  = "!="
    value     = "nfs-server"
  }

  # Ensure tasks run on different hosts
  constraint {
    distinct_hosts = true
  }

  # Spread tasks across nodes
  spread {
    attribute = "${node.unique.name}"
    weight    = 50
  }

  # Update strategy
  update {
    stagger      = "10s"
    max_parallel = 1
    health_check = "checks"
    min_healthy_time = "10s"
    healthy_deadline = "3m"
    progress_deadline = "10m"
    auto_revert = true
    auto_promote = false
    canary = 0
  }

  group "${__SERVICE__}-${__ENVIRONMENT__}" {
    count = ${__COUNT__} # ${__COUNT__:-1} # envsubst will only ever replace references to environment variables in the form of ${VAR} or $VAR. Special shell features like ${VAR:-default} are not supported.

    network {
      port "http" {
        # Dynamic port allocation (can be overridden in service-specific templates)
      }
    }

    task "${__SERVICE__}-${__ENVIRONMENT__}" {
      driver = "${__JOB_DRIVER__}"

      config {
        image        = "${__IMAGE_NAME__}:${__IMAGE_TAG__}"
        force_pull   = "${__IMAGE_FORCE_PULL__}"
        ports        = ["http"]
        network_mode = "bridge"
        
        # Registry authentication (if needed)
        auth {
          username       = "${__USERNAME__}"
          password       = "${__PASSWORD__}"
          server_address = "${__CI_REGISTRY__}"
        }
      }

      # Environment variables (service-specific templates should extend this)
      env {
        CI_ENVIRONMENT_NAME = "${__ENVIRONMENT__}"
        SERVICE_NAME        = "${__SERVICE__}"
      }

      # Resources (can be overridden)
      resources {
        cpu    = ${__RESOURCE_CPU__} # ${__RESOURCE_CPU__:-500} # envsubst will only ever replace references to environment variables in the form of ${VAR} or $VAR. Special shell features like ${VAR:-default} are not supported.
        memory = ${__RESOURCE_MEMORY__} # ${__RESOURCE_MEMORY__:-512}
      }

      # Restart policy
      restart {
        attempts = 3
        interval = "5m"
        delay    = "15s"
        mode     = "delay"
      }
    }

    # Service definition
    # Tags are set via __SERVICE_TAGS__ variable (generated by deployment script)
    # - External access: Full Traefik tags for routing
    # - Internal only: Simple tags like ["api"]
    service {
      name                = "${__SERVICE__}-${__ENVIRONMENT__}"
      provider            = "nomad"
      port                = "http"
      tags                = ${__SERVICE_TAGS__}
      enable_tag_override = true

      # Health check
      check {
        type     = "http"
        port     = "http"
        path     = "${__HEALTH_CHECK_PATH__:-/health}"
        interval = "10s"
        timeout  = "2s"
        method   = "GET"
      }

      # Readiness check
      check {
        type     = "http"
        port     = "http"
        path     = "${__READINESS_CHECK_PATH__:-/ready}"
        interval = "10s"
        timeout  = "2s"
        method   = "GET"
      }
    }
  }
}

